export const names = [
    "Brietta",
    "Pollyanna",
    "Derron",
    "Lucio",
    "Clair",
    "Englebert",
    "Blisse",
    "Earle",
    "Nicole",
    "Cariotta",
    "Lauraine",
    "Sandye",
    "Gordie",
    "Abeu",
    "Carmelina",
    "Garner",
    "Manon",
    "Quentin",
    "Devon",
    "Lezlie",
    "Gwenette",
    "Zaria",
    "Rafaela",
    "Guglielma",
    "Elisha",
    "Rosabelle",
    "Horatius",
    "Hugibert",
    "Thaxter",
    "Alida",
    "Brittne",
    "Emilie",
    "Noelyn",
    "Hercules",
    "Debra",
    "Irwinn",
    "Kristofer",
    "Verla",
    "Antonetta",
    "Sheff",
    "Ethe",
    "Maurizio",
    "Rozina",
    "Stanislaw",
    "Mickie",
    "Harcourt",
    "Boniface",
    "Ives",
    "Jasun",
    "Marget",
    "Berget",
    "Conroy",
    "Mabel",
    "Andonis",
    "Mellicent",
    "Ezri",
    "Geordie",
    "Michale",
    "Derron",
    "Lucio",
    "Clair",
    "Englebert",
    "Blisse",
    "Earle",
    "Nicole",
    "Cariotta",
    "Lauraine",
    "Sandye",
    "Gordie",
    "Abeu",
    "Carmelina",
    "Garner",
    "Manon",
    "Quentin",
    "Devon",
    "Lezlie",
    "Gwenette",
    "Zaria",
    "Rafaela",
    "Guglielma",
    "Elisha",
    "Rosabelle",
    "Horatius",
    "Hugibert",
    "Thaxter",
    "Alida",
    "Brittne",
    "Emilie",
    "Noelyn",
    "Hercules",
    "Debra",
    "Irwinn",
    "Kristofer",
    "Verla",
    "Antonetta",
    "Sheff",
    "Ethe",
    "Maurizio",
    "Rozina",
    "Stanislaw",
    "Mickie",
    "Harcourt",
    "Boniface",
    "Ives",
    "Jasun",
    "Marget",
    "Berget",
    "Conroy",
    "Mabel",
    "Andonis",
    "Mellicent",
    "Ezri",
    "Geordie",
    "Michale",
    "Hamil",
    "Barbara",
    "Krishnah",
    "Marcelle",
    "Normy",
    "Roddy",
    "Vin",
    "Hart",
    "Ileana",
    "Gleda",
    "Peadar",
    "Den",
    "Frank",
    "Valry",
    "Bastian",
    "Mordy",
    "Holly",
    "Estele",
    "Westley",
    "Darleen",
    "Claus",
    "Lowrance",
    "Rosetta",
    "Sarita",
    "Mord",
    "Base",
    "Amii",
    "Antonietta",
    "Wye",
    "Horten",
    "Portie",
    "Owen",
    "Leoine",
    "Harlie",
    "Alic",
    "Camella",
    "Timi",
    "Leanora",
    "Brandy",
    "Del",
    "Hamil",
    "Barbara",
    "Krishnah",
    "Marcelle",
    "Normy",
    "Roddy",
    "Vin",
    "Hart",
    "Ileana",
    "Gleda",
    "Peadar",
    "Den",
    "Frank",
    "Valry",
    "Bastian",
    "Mordy",
    "Holly",
    "Estele",
    "Westley",
    "Darleen",
    "Claus",
    "Lowrance",
    "Rosetta",
    "Sarita",
    "Mord",
    "Base",
    "Amii",
    "Antonietta",
    "Wye",
    "Horten",
    "Portie",
    "Owen",
    "Leoine",
    "Harlie",
    "Alic",
    "Camella",
    "Timi",
    "Leanora",
    "Brandy",
    "Del",
    "Ervin"
]

export const extraColorArray = ['FF6633', 'FFB399', 'FF33FF', 'FFFF99', '00B3E6',
    'E6B333', '3366E6', '999966', '99FF99', 'B34D4D',
    '80B300', '809900', 'E6B3B3', '6680B3', '66991A',
    'FF99E6', 'CCFF1A', 'FF1A66', 'E6331A', '33FFCC',
    '66994D', 'B366CC', '4D8000', 'B33300', 'CC80CC',
    '66664D', '991AFF', 'E666FF', '4DB3FF', '1AB399',
    'E666B3', '33991A', 'CC9999', 'B3B31A', '00E680',
    '4D8066', '809980', 'E6FF80', '1AFF33', '999933',
    'FF3380', 'CCCC00', '66E64D', '4D80CC', '9900B3',
    'E64D66', '4DB380', 'FF4D4D', '99E6E6', '6666FF'];

export function shuffle(array) {
    let currentIndex = array.length, randomIndex;

    // While there remain elements to shuffle...
    while (currentIndex !== 0) {

        // Pick a remaining element...
        randomIndex = Math.floor(Math.random() * currentIndex);
        currentIndex--;

        // And swap it with the current element.
        [array[currentIndex], array[randomIndex]] = [
            array[randomIndex], array[currentIndex]];
    }

    return array;
}